#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 07:42:56 2019

@author: tkhacker
"""

import numpy as np
import pandas as pd

arr_pand = np.random.randint(0, 10, 6).reshape(2, 3)

df1 = pd.DataFrame(arr_pand)

s1 = df1[0]
s2 = df1[1]
s3 = df1[2]

df1[3] = pd.Series([1,2])

df1[4] = df1[0] * df1[1]

datos_fisicos = pd.DataFrame(arr_pand, columns=['Estatura (cm)',
                                                'Peso (kg)',
                                                'Edad (anios)'])

datos_fisicos2 = pd.DataFrame(
        arr_pand, 
        columns=[
                'Estatura (cm)',
                'Peso (kg)',
                'Edad (anios)'],
        index=['Adrian', 'Vicente'])

df1.index = ['Adrian', 'Vicente']
df1.columns = ['A', 'B', 'C', 'D', 'F']